name: CI

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Force Docker socket for Testcontainers
        run: |
          echo "DOCKER_HOST=unix:///var/run/docker.sock" >> $GITHUB_ENV
          echo "TESTCONTAINERS_DOCKER_SOCKET_OVERRIDE=/var/run/docker.sock" >> $GITHUB_ENV

      - name: Docker diagnostics
        run: |
          docker version
          docker info

      - name: Enable Testcontainers Reuse
        run: echo "testcontainers.reuse.enable=true" > ~/.testcontainers.properties

      - name: Start Docker Compose
        run: |
          docker compose -f src/main/docker/docker-compose.keycloak.yml up -d
          docker compose -f src/main/docker/docker-compose.minio.yml up -d

      - name: Wait for services
        run: sleep 30

      - name: Build with Gradle
        run: ./gradlew build
